// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AuthLoginPageData, AuthLoginPageResponse, AuthOauthCallbackResponse, AuthLogoutResponse, AuthPublicKeysResponse, LlmsVideosPostData, LlmsVideosPostResponse, LlmsVideosGetResponse, LlmsProcessChatData, LlmsProcessChatResponse, LlmsParseVoiceData, LlmsParseVoiceResponse, UsersReadUsersData, UsersReadUsersResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse } from './types.gen';

export class AuthService {
    /**
     * Login Page
     * Redirect to Keycloak login page.
     * @param data The data for the request.
     * @param data.redirectTarget
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static loginPage(data: AuthLoginPageData = {}): CancelablePromise<AuthLoginPageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/login',
            query: {
                redirect_target: data.redirectTarget
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Oauth Callback
     * Authorize user with Keycloak access token.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static oauthCallback(): CancelablePromise<AuthOauthCallbackResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/callback'
        });
    }
    
    /**
     * Logout
     * Deauthorize user and redirect to logout page.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static logout(): CancelablePromise<AuthLogoutResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/logout'
        });
    }
    
    /**
     * Public Keys
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static publicKeys(): CancelablePromise<AuthPublicKeysResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/certs'
        });
    }
}

export class LlmsService {
    /**
     * Videos Post
     * Create video generation job.
     * @param data The data for the request.
     * @param data.userId
     * @returns VideoObject Successful Response
     * @throws ApiError
     */
    public static videosPost(data: LlmsVideosPostData): CancelablePromise<LlmsVideosPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/llms/videos',
            query: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Videos Get
     * Get video generation job status and result, if completed.
     * @returns VideoObject Successful Response
     * @throws ApiError
     */
    public static videosGet(): CancelablePromise<LlmsVideosGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/llms/videos'
        });
    }
    
    /**
     * Process Chat
     * Process chat message and return response.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ChatResponse Successful Response
     * @throws ApiError
     */
    public static processChat(data: LlmsProcessChatData): CancelablePromise<LlmsProcessChatResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/llms/process_chat',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Parse Voice
     * Parse voice input and return streamed voice response.
     * @param data The data for the request.
     * @param data.formData
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static parseVoice(data: LlmsParseVoiceData): CancelablePromise<LlmsParseVoiceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/llms/parse_voice',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublicKC Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}