// This file is auto-generated by @hey-api/openapi-ts

export type Body_llms_parse_voice = {
    audio: (Blob | File);
};

export type ChatRequest = {
    message: string;
};

export type ChatResponse = {
    response: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserPublicKC = {
    name: string;
    email: string;
    created_at?: (string | null);
    is_superuser?: boolean;
    id: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Represents a generated video object.
 */
export type VideoObject = {
    id: string;
    object: "video";
    status: string;
    created_at?: (number | null);
    completed_at?: (number | null);
    expires_at?: (number | null);
    error?: ({
    [key: string]: unknown;
} | null);
    progress?: (number | null);
    remixed_from_video_id?: (string | null);
    seconds?: (string | null);
    size?: (string | null);
    model?: (string | null);
    usage?: ({
    [key: string]: unknown;
} | null);
};

export type AuthLoginPageData = {
    redirectTarget?: (string | null);
};

export type AuthLoginPageResponse = (unknown);

export type AuthOauthCallbackResponse = (unknown);

export type AuthLogoutResponse = (unknown);

export type AuthPublicKeysResponse = ({
    [key: string]: unknown;
});

export type LlmsVideosPostData = {
    userId: string;
};

export type LlmsVideosPostResponse = (VideoObject);

export type LlmsVideosGetResponse = (VideoObject);

export type LlmsProcessChatData = {
    requestBody: ChatRequest;
};

export type LlmsProcessChatResponse = (ChatResponse);

export type LlmsParseVoiceData = {
    formData: Body_llms_parse_voice;
};

export type LlmsParseVoiceResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublicKC);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);